version: '3'
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./ApiGatewayService
    ports:
      - "3001:3001"

  auth-service:
    container_name: auth-service
    build:
      context: ./AuthService
    # ports:
    #   - "3001:3001"

  matching-service:
    container_name: matching-service
    build:
      context: ./MatchingService
    ports:
      - "3005:3005"
    stdin_open: true

  question-service:
    container_name: question-service
    build:
      context: ./QuestionService
    # ports:
    #   - "3001:3001"

  user-service:
    container_name: user-service
    build:
      context: ./UserService
    # ports:
    #   - "3001:3001"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"