version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    image: frontend-image
    ports:
      - "3000:3000"

  api-gateway:
    container_name: api-gateway
    build:
      context: ./ApiGatewayService
    image: api-gateway-image
    ports:
      - "3001:3001"

  question-service:
    container_name: question-service
    build:
      context: ./QuestionService
    image: question-service-image

  auth-service:
    container_name: auth-service
    build:
      context: ./AuthService
    image: auth-service-image

  user-service:
    container_name: user-service
    build:
      context: ./UserService
    image: user-service-image