version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ../frontend
    image: szelongq/peerprep-frontend:latest
    ports:
      - "3000:3000"
    platform: linux/amd64
      
  api-gateway:
    container_name: api-gateway
    build:
      context: ../ApiGatewayService
    image: szelongq/peerprep-api-gateway:latest
    ports:
      - "3001:3001"
    platform: linux/amd64

  auth-service:
    container_name: auth-service
    build:
      context: ../AuthService
    image: szelongq/peerprep-auth-service:latest
    platform: linux/amd64

  question-service:
    container_name: question-service
    build:
      context: ../QuestionService
    image: szelongq/peerprep-question-service:latest
    platform: linux/amd64

  user-service:
    container_name: user-service
    build:
      context: ../UserService
    image: szelongq/peerprep-user-service:latest
    platform: linux/amd64

  matching-service:
    container_name: matching-service
    build:
      context: ../MatchingService
    image: szelongq/peerprep-matching-service:latest
    ports:
      - "3005:3005"
    stdin_open: true
    platform: linux/amd64
    
  chat-service:
    container_name: chat-service
    build:
      context: ../ChatService
    image: szelongq/peerprep-chat-service:latest
    ports:
      - "3007:3007"
    platform: linux/amd64
