apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: szelongq/peerprep-frontend:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: env-config
        resources:
          limits:
            cpu: 1Gi
            ephemeral-storage: 1Gi
            memory: 4Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        ports:
        - containerPort: 3000
