apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
      - name: question-service
        image: question-service-image
        imagePullPolicy: IfNotPresent
        # ports:
        # - containerPort: 3001