apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
      - name: matching-service
        image: matching-service-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3005