apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: api-gateway-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001