export const QUESTION_CATEGORIES = [
    "Algorithm",
    "Data Structure",
    "Array",
    "String",
    "Hash Table",
    "Dynamic Programming",
    "Math",
    "Sorting",
    "Greedy",
    "Depth-First Search",
    "Binary Search",
    "Database",
    "Breadth-First Search",
    "Tree",
    "Matrix",
    "Two Pointers",
    "Bit Manipulation",
    "Binary Tree",
    "Heap (Priority Queue)",
    "Stack",
    "Prefix Sum",
    "Graph",
    "Simulation",
    "Design",
    "Counting",
    "Sliding Window",
    "Backtracking",
    "Union Find",
    "Linked List",
    "Enumeration",
    "Ordered Set",
    "Monotonic Stack",
    "Trie",
    "Recursion",
    "Divide and Conquer",
    "Number Theory",
    "Bitmask",
    "Queue",
    "Binary Search Tree",
    "Segment Tree",
    "Memoization",
    "Geometry",
    "Binary Indexed Tree",
    "Topological Sort",
    "Game Theory",
    "Hash Function",
    "Combinatorics",
    "Shortest Path",
    "Interactive",
    "String Matching",
    "Data Stream",
    "Rolling Hash",
    "Brainteaser",
    "Randomized",
    "Monotonic Queue",
    "Merge Sort",
    "Iterator",
    "Concurrency",
    "Doubly-Linked List",
    "Probability and Statistics",
    "Quickselect",
    "Bucket Sort",
    "Suffix Array",
    "Minimum Spanning Tree",
    "Counting Sort",
    "Shell",
    "Line Sweep",
    "Reservoir Sampling",
    "Strongly Connected Component",
    "Eulerian Circuit",
    "Radix Sort",
    "Rejection Sampling",
    "Biconnected Component"
]
