export const QUESTION_CATEGORIES = [
    "Array",
    "String",
    "Hash Table",
    "Math",
    "Dynamic Programming",
    "Sorting",
    "Greedy",
    "Depth-First Search",
    "Binary Search",
    "Database",
    "Breadth-First Search",
    "Tree",
    "Matrix",
    "Two Pointers",
    "Binary Tree",
    "Bit Manipulation",
    "Heap (Priority Queue)",
    "Stack",
    "Prefix Sum",
    "Graph",
    "Counting",
    "Backtracking",
    "Sliding Window",
    "Union Find",
    "Linked List",
    "Ordered Set",
    "Enumeration",
    "Monotonic Stack",
    "Trie",
    "Recursion",
    "Divide and Conquer",
    "Number Theory",
    "Bitmask",
    "Queue",
    "Binary Search Tree",
    "Memoization",
    "Geometry",
    "Topological Sort",
    "Binary Indexed Tree",
    "Game Theory",
    "Hash Function",
    "Shortest Path",
    "Combinatorics",
    "String Matching",
    "Data Stream",
    "Rolling Hash",
    "Randomized",
    "Monotonic Queue",
    "Merge Sort",
    "Iterator",
    "Concurrency",
    "Doubly-Linked List",
    "Probability and Statistics",
    "Quickselect",
    "Bucket Sort",
    "Minimum Spanning Tree",
    "Counting Sort",
]