apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service-deployment
  namespace: peerprep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
      - name: question-service
        image: szelongq/peerprep-question-service:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi