apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: peerprep
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007
  type: LoadBalancer
