apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: szelongq/peerprep-chat-service:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        ports:
        - containerPort: 3007
